/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/interview/$id': typeof InterviewIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/interview/$id': typeof InterviewIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/interview/$id': typeof InterviewIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/interview/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/interview/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/interview/$id'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  InterviewIdRoute: typeof InterviewIdRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  InterviewIdRoute: InterviewIdRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
